export { fetchVacancies, useVacanciesQuery } from './api/fetch-vacancies.api'
export { markVacancyViewed, useMarkVacancyViewedMutation } from './api/mark-vacancy-viewed.api'
export { markVacancyApplied, useMarkVacancyAppliedMutation } from './api/mark-vacancy-applied.api'
export { hideVacancy, useHideVacancyMutation } from './api/hide-vacancy.api'
export { generateCoverLetter, useGenerateCoverLetterMutation } from './api/generate-cover-letter.api'
